# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('careerform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 8, 5, 57, 18, 484868, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
