# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerform', '0005_auto_20160708_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cvfile',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
