# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerform', '0006_auto_20160708_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='cvfile',
            new_name='file',
        ),
    ]
