# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerform', '0007_auto_20160708_1423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='career',
            table='profile',
        ),
    ]
