# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:14
from __future__ import unicode_literals

import apps.article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.article.models.upload_location, width_field='width_field')),
                ('slug', models.SlugField(unique=True)),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.CategoryModel')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
