# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='publish_date',
        ),
    ]
